.github/workflows/elixir.yml, CHANGELOG.md, README.md, config/config.exs, lib/data_layer.ex, lib/repo.ex, mix.exs, priv/test_repo/migrations/20200903065656_add_posts.exs, priv/test_repo/migrations/20200903065659_add_comments.exs, test/ash_postgres_test.exs, test/filter_test.exs, test/support/repo_case.ex, test/support/test_repo.ex, test/test_helper.exs
For example: `fix: Multiply by appropriate coefficient`, or
`feat(Calculator): Correctly preserve history`
Any explanation or long form information in your commit message should be
in a separate paragraph, separated by a blank line from the primary message
=> test: Start test suite

lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, lib/migration_generator/phase.ex
=> fix: drop constraints outside of phases

lib/migration_generator/migration_generator.ex, lib/mix/tasks/ash_postgres.generate_migrations.ex, test/migration_generator_test.exs
=> Multiple snapshots

lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, test/migration_generator_test.exs
Before merging this, I'd like to change the default behaviour of integer_primary_key over in ash-project/ash. It currently defaults `allow_nil?` to true, which is incompatible with :serial
fixes #32
=> Make integer serial if generated

lib/migration_generator/operation.ex, test/migration_generator_test.exs
This works fine but the implementation isn't too nice. Alternative ideas?
=> Omit field opts if they are default values

lib/migration_generator/migration_generator.ex
Use `ecto_sql`'s formatter config when generating migrations. 
I'm using `File.cwd!/1` here, as suggested by José:
> if the project is being compiled with Mix, "File.cwd!" will always point to the root directory because Mix always runs from root
(https://groups.google.com/g/elixir-lang-talk/c/Ls0eJDdMMW8/m/VLWWAKWPAQAJ)
=> Use ecto_sql formatter settings

lib/migration_generator/operation.ex
Joining this
```elixir
"references(#{inspect(table)}",
[
"type: #{inspect(attribute.type)}",
"column: #{inspect(destination_field)}",
"with: [#{source_attribute}: :#{destination_attribute}]"
],
")",
```
currently generates a function call ending with `, )`.
=> Fix incorrect joins

lib/repo.ex
Made AshPostgres.Repo.init/2 overridable so that one can do custom things before calling super inside init/2.
=> fix: Made AshPostgres.Repo.init/2 overridable

lib/migration_generator/operation.ex, test/migration_generator_test.exs
Sets the autoincrement keys as `:bigserial`, this is common standard for Ecto as well
=> improvement: primary autoincrement key as bigserial

lib/migration_generator/migration_generator.ex
A new PR as I messed up the Git history on the old one. I've deleted the `priv/` folder and run the migrations, but I'm still getting this:
```elixir
def up do
create table(:posts, primary_key: false) do
add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
add :title, :text
add :score, :bigint
add :public, :boolean
add :category, :citext
add :type, :text, default: "sponsored"
add :price, :bigint
end
create constraint(:posts, :price_must_be_positive, check: "type = 'sponsored' AND price > 0")
alter table(:posts) do
add :decimal, :decimal, default: 0
add :status, :status
end
```
=> improvement: Preserve attribute order

lib/functions/fragment.ex, test/filter_test.exs
Let me know what kind of testing needs to be done and I can see what I can do.
=> fix: fix fragment processing broken

test/load_test.exs
Following up from the similar refactor in Ash, removing the "side loading" language from code.
=> refactor: remove references to "side loading"

.formatter.exs, lib/ash_postgres.ex, lib/data_layer.ex
Add support for defining the names of pre-existing exclusion constraints in the DB
Signed-off-by: kernel <kernel-io@users.noreply.github.com>
=> improvement: add exclusion_constraint_names

README.md
The current opening paragraph leaves quite a lot of ambiguity in the reader's mind about whether this might continue to be supported. I've updated the wording to be much more direct to remove any doubt.
- Update some formatting too
=> docs: Add clarifying language to README

lib/ecto_migration_default.ex, lib/migration_generator/migration_generator.ex, test/migration_generator_test.exs
Instead of hard defaulting to a `nil` default value when there is no
available protocol implementation for the type, we provide a more
sensible default as a protocol fallback.
=> improvement: handle fallback ecto migration default elegantly

lib/migration_generator/operation.ex, test/migration_generator_test.exs
I noticed an issue when generating a migration that renamed an attribute, it was generating migrations that looked like this:
```
defmodule MyApp.Repo.Migrations.MigrateResources36 do
@moduledoc """
Updates resources based on their most recent snapshots.
This file was autogenerated with `mix ash_postgres.generate_migrations`
"""
use Ecto.Migration
def up do
rename table(:element_steps), :description, to: :something_else
end
def down do
rename table(:element_steps), :description, to: :something_else
end
end
```
And obviously the down migration should rename back the other way. 
I tracked it down to a double-reassign in the migration generator - the `new_attribute` was being stored as `old_attribute` then being passed back as the `new_attribute`, ie. the exact same data. The swapping …
=> fix: rename attributes correctly in down migration

lib/migration_generator/migration_generator.ex
I accidentally generated a migration with a dasherised name.  This fixes that.
=> fix: Squash dashes in migration names.

lib/expr.ex, test/calculation_test.exs
The `&&` operator was being expanded to `ash_elixir_or` instead of `ash_elixir_and`. Fixed the source and test.
=> fix: && operator in expressions to point to ash_elixir_and

test/aggregate_test.exs, test/support/resources/profile.ex
Refs #120 
Aggregates on array composite types are failing in two ways:
1. When the array contains something, the aggregate results in nil
2. When the array is empty, `ERROR 2202E (array_subscript_error) cannot accumulate empty arrays` is raised
=> Failing tests for aggregates on arrays

lib/expr.ex, test/calculation_test.exs, test/support/resources/author.ex
`string_join` in the data layer (see https://github.com/ash-project/ash/pull/515)
I've dumped some tests in calculation_test.exs, but I wonder if that's the right place? Oh, also, I'm not sure about the params getting passed on to the next call to do_dynamic_expr, (bindings, embedded)? I C&P that without understanding what's going on there.
=> improvement: Implement string_join expr

lib/migration_generator/operation.ex, lib/migration_generator/phase.ex
Currently in `MigrationGenerator.Phase` a table name interpolated as simply `:#{table}` for `Create.up`, `Alter.up/down`, but in `Create.down` it is done as `:#{inspect(table)}`. If a table name contains non-word letters then without that inspect call the result may end up being an invalid code - `:auth.tokens` (if the table name is "auth.tokens") versus legal `:"auth.tokens"`.
Seems like having non-word letters might be a bad idea, still, a simple fix.
=> fix: interpolate table names with `inspect` in generated migrations

documentation/topics/postgres-expressions.md
Fixed docs for postgres `like` operator
=> chore: fixed incorrect docs

lib/ecto_migration_default.ex
Use Logger.warning instead of Logger.warn, [which is deprecated as of elixir 1.15](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#logger-2).
Logger.warning [is available since elixir 1.11](https://hexdocs.pm/logger/1.15.0/Logger.html#warning/2), and since [this project requires at least elixir 1.11](https://github.com/ash-project/ash_postgres/blob/main/mix.exs#L15), this is a safe change.
=> fix: fix Logger deprecations for elixir 1.15

lib/custom_index.ex, lib/data_layer.ex
Adds ability to pass single atom/string to `index` dsl. (So maybe it is an improvement, not a fix, but it is really small, don't know.)
While at it replaced custom validations that are not needed anymore (and one of them contained outdated field name `manages_tenant`).
=> fix: use `:wrap_list` type instead of custom validaitons

lib/migration_generator/operation.ex, test/migration_generator_test.exs
In multitenant resources migration's generation, check if the relationship points at the primary key of the target then not adding the multitenancy attribute (resolving #144 and #157)
=> Multitenant references

.formatter.exs, documentation/dsls/DSL:-AshPostgres.DataLayer.cheatmd, lib/data_layer.ex, lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, lib/reference.ex, lib/transformers/prevent_attribute_multitenancy_and_non_full_match_type.ex, test/migration_generator_test.exs, test/references_test.exs
* improvement: add match_with option on references
* improvement: add match_type option on references
Submitting this as a draft to get some early feedback given it's my first contribution.
What still needs to be done:
=> improvement: allow specifying multi-column foreign keys

test/calculation_test.exs, test/support/resources/author.ex
I ran into this error problem today and spent several hours reviewing the code. 
I was able to narrow it down to somewhere around here:
https://github.com/ash-project/ash_postgres/blob/944a4e128eef25fe3531964bceb23e916d66fbed/lib/expr.ex#L1027
I tried to update the `at_path` property of the `exists` with the relationship path, but afterwards, I still got an error because the parent in the constructed subquery was `nil`. 
I added this after `Ash.Filter.update_aggregates(...)`
```elixir
|> update_exists(fn exists ->
%{exists | at_path: relationship_path || []}
end),
.....
defp update_exists(expression, mapper) do
case expression do
%{__function__?: true, arguments: args} = func ->
%{func | arguments: Enum.map(args, &update_exists(&1, mapper))}
%Exists{} = exists ->
mapper.(exists)
other -> …
```
=> Add test, that shows bug when filtering on exists calc on related resource

lib/aggregate.ex, lib/custom_index.ex, lib/join.ex, lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, test/migration_generator_test.exs
Right now fields of `custom_index` are first transformed into atoms and then during migration generation into strings. 
I used a field named "order" and encountered an error because of this. Ecto generates different statements depending on whenever a field was provided as a string or as an atom:
```elixir
create index(:some_table, ["order"]) # invalid
create index(:some_table, [:order]) # valid
```
For atoms the resulting name will be in quotes, for strings they will be left as is (and it, for example, allows specifying things like `"name gin_trgm_ops"` for full-text search usage).
So it makes sense to keep user provided input as is and not convert it into atoms or strings.
Also made `RemoveCustomIndex` operation to use reverse direction of `AddCustomIndex` to avoid repetition.
=> fix: keep fields of `custom_index` in format that they were provided

lib/data_layer.ex, test/distinct_test.exs
When upgrading dependencies on my project recently, one of our queries started to fail with a `no case clause matching` error. The query in question had a simple filter with a distinct clause and *no* sort clause. 
Basically, I found that the shape of the return in `DataLayer.get_distinct_statement` was inconsistent. I created a test that exposed the issue with the distinct alone. And while I was making sure all exit paths were accounted for I noticed that the success path in the `reduce_while` was never ran, the fallback was always used: 
```elixir
distinct_on
|> Enum.reduce_while({sort, [], [], Enum.count(distinct.params), query}, fn
_, {[], _distinct_statement, _, _count, _query} ->
{:halt, :error}
distinct_on, {[order_by | rest_order_by], distinct_statement, params, count, query} -> …
```
=> fix: Correct the matching used in building a distinct expression

test/manual_update_test.exs, test/support/resources/post.ex
This regression occurs as of https://github.com/ash-project/ash/commit/b01168b59753800806cd0c1faf6a9de931ffe1e0
I wasn't able to reproduce it directly in `ash`, so it appears to also involve `ash_postgres`.
=> test: add failing test to demonstrate bug with manual updates

test/manual_update_test.exs, test/support/resources/post.ex
Add a failing test to demonstrate an issue recently introduced, where calling `Ash.Changeset.load` does not work.
=> test: add failing test to demo bug with changeset loading related data

lib/repo.ex
As per the documentation (and indeed the actual behavior):
> Extensions can be a string, representing a standard postgres
extension, or a module that implements `AshPostgres.CustomExtension`.
This doesn't affect runtime behavior. Testing against type-related warnings for supported scenarios might be worthwhile, but it seems outside of the reasonable scope of this fix. Happy to add tests if there is a reasonable quick path to that.
=> Include modules in installed_extensions return type

test/rel_with_parent_filter_test.exs, test/support/resources/author.ex
Added a test for something we tried in our application, but didn't get the expected output. 
Not sure if we didn't understand `parent` correctly or if it is a bug. At least the aggregate result differs from what is returned when loading the relationship, which seems a bit inconsistent.
=> add test for parent in relationship filter

lib/join.ex
`context` is taken from a root query. If a root query is of polymorphic resource then it will contain `data_layer.table`. It should not be propagated into context of a join subquery otherwise it will use a root resource table for a related resource.
=> fix: use proper tables in joins originating from polymorphic resource

lib/migration_generator/operation.ex
before fix, it generates wrong index name in down migration, especially multitenant case.
i just made code same as up migration.
=> fix: generate correct custom index name in down migration function

lib/custom_index.ex, lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, test/migration_generator_test.exs
I'm so sorry that I misunderstood `nulls_distinct` option in #221.
This PR fix the defulat of `nulls_distinct` option to `true`.
=> Fix default of nulls_distinct option to true

lib/migration_generator/migration_generator.ex
> In cases where the database server is not set to UTC, this fixes timezone inconsistencies when adding timestamp columns to tables with existing data, that would then have their timestamps set to non-UTC times.
Something I noticed in dev - when adding `inserted_at`/`updated_at` timestamps to a table, it generated a migration that looked like this:
```
alter table(:posts) do
add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
end
```
I am in UTC+8, and I presume my dev database server is as well. So when I ran this migration at 12.01pm local time for an existing table that had data in it, the existing rows had their timestamps set to `2023-02-15 12:01:39.984484`.
However, when inserting …
=> fix: Use UTC for default generated timestamps

documentation/tutorials/get-started-with-postgres.md
- Remove repeated block of code in calculations section
- Calculations can refer _aggregates_ (am I correct that this is a typo? maybe I'm misinterpreting)
=> Improve get started tutorial

documentation/tutorials/get-started-with-postgres.md
using the --name attribute gives the following error:
```
mix ash.codegen --name add_representatives_and_relations
Getting extensions in current project...
Running codegen for AshPostgres.DataLayer...
warning: Name must be provided when generating migrations, unless `--dry-run` or `--check` is also provided.
Using an autogenerated name will be deprecated in a future release.
Please provide a name. for example:
mix ash_postgres.generate_migrations <name> 
(ash_postgres 2.0.0-rc.10) lib/mix/tasks/ash_postgres.generate_migrations.ex:112: Mix.Tasks.AshPostgres.GenerateMigrations.run/1
(mix 1.16.2) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
(elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.16.2) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
(mix …
```
=> align ash.codegen params with current version

test/bulk_create_test.exs, test/bulk_update_test.exs, test/support/resources/record.ex
- bulk_create returns a Postgrex error instead of Ash.Error.Changes.Required like the non-bulk create does
- bulk_update with :stream strategy does the same
- bulk_update with :atomic strategy doesn't trim the empty string and writes it to the database
=> chore: add failing test for bulk actions and non-null violations

test/calculation_test.exs, test/support/resources/post.ex
Additional test that only increases test coverage.
I encountered a weird behaviour in our code base where a `caluclation` using an `exists` as defined in this PR would not return `true` even if the relation exists.
I wrote a test case directly in `ash_postgres` trying to reproduce the behaviour. However, I could not reproduce it. The test case now only serves to increase the test coverage and proves that the features behaves as expected.
=> feat: test with calculations using `exists`

test/calculation_test.exs, test/support/resources/author.ex
In this case the exist is only loaded in the state of the second calculation and the result is used for both.
=> show error with calc depending on other exists calc

lib/mix/tasks/ash_postgres.rollback.ex
- When using mix command: `mix ash.rollback` and then enter 1 ash_postgres.rollback doing 2 step rollback.
- Or use ash_postgres rollback with repo defined : `mix ash_postgres.rollback -r MyApp.Repo`
=> fix: remove duplicate repo flags

documentation/dsls/DSL:-AshPostgres.DataLayer.md, documentation/topics/resources/references.md, lib/data_layer.ex, lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, lib/reference.ex, test/migration_generator_test.exs
Introduce the possibility to specify which columns of a foreign key should be set to NULL when the referenced resource is deleted: `on_delete: {:nilify, columns}`.
This provides more fine-grained control over the `on_delete: :nilify`  option for configuring the foreign key constraint, where the default behavior is to set all columns of the foreign key to `NULL`.
This is useful for example in cases where multitenancy is employed on resources, and a resource A has a `(tenant_id, resource_b_id)` foreign key that references the `tenant_id` and `id` columns of resource B: when the resource B is deleted, we'd like to nilify only the `resource_b_id` column of resource A and not its `tenant_id`.
Note: this functionality is supported by Ecto's `on_delete: {:nilify, columns}` option and ultimately …
=> improvement: support `on_delete: :nilify` for specific columns

documentation/topics/resources/references.md
=> docs: Clarify that `references` go inside a `postgres` block

test/complex_calculations_test.exs, test/support/complex_calculations/resources/certification.ex, test/support/complex_calculations/resources/skill.ex
The test produces the following:
```elixir
1) test complex aggregates (AshPostgres.Test.ComplexCalculationsTest)
test/complex_calculations_test.exs:66
** (Ash.Error.Unknown) Unknown Error
* ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.
** (Ecto.QueryError) could not find named binding `parent_as(false)` in query:
from c0 in AshPostgres.Test.ComplexCalculations.Certification,
as: 0,
left_lateral_join: s1 in subquery(from s0 in AshPostgres.Test.ComplexCalculations.Skill,
as: 0,
left_lateral_join: d1 in subquery(from d0 in AshPostgres.Test.ComplexCalculations.Documentation,
as: 0,
where: parent_as(false).id == as(0).skill_id,
where: type(
as(0).status,
{:parameterized, …
```
=> test: add failing test to demonstrate an error with nested aggregates

lib/migration_generator/migration_generator.ex, lib/mix/tasks/ash_postgres.squash_snapshots.ex, test/mix_squash_snapshots_test.exs
Implements  #301.
Note: I put `--into last` as default behavior. So by default it just removes old snapshots leaving one. Which is not helpful for multi-branch thing, but, I guess, makes sense in terms of cleaning up.
=> improvement: add `ash_postgres.squash_snapshots` mix task

lib/mix/tasks/ash_postgres.install.ex
This PR fixes an ordering typo when passing arguments to `configure_runtime` as well as changes the placeholder for `Helpdesk.Repo` to be the repo argument.
=> fix: configure_runtime/3 in ash_postgres.install

lib/mix/tasks/ash_postgres.install.ex
It seems that my recent PR had a nasty little typo that actually broke the installer. Sorry about that :grimacing:. (I had it fixed locally but seems that I had forgotten to push the change to my fork.)
=> fix: typo in configure_runtime/3

lib/mix/tasks/ash_postgres.install.ex
This is a minor improvement that checks whether `installed_extensions/0` already exists in the repo module before adding it. This is only an issue when an igniter installer is run twice, but I faced it once so just thought it'd be great to catch it.
=> fix: check for existing installed_extensions/0 in ash_postgres.install

lib/mix/tasks/ash_postgres.install.ex
Minor fix to avoid a nested `defmodule` definition inside the generated `Repo` module file.
=> fix: default_repo_contents in ash_postgres.install

lib/custom_index.ex
Unfortunately it's not an option on indexes in PostgreSQL 14 :( 
https://www.postgresql.org/docs/14/sql-createindex.html
=> docs: Add note that `nulls_distinct` requires PostgreSQL 15

lib/data_layer.ex, test/bulk_create_test.exs, test/create_test.exs, test/support/resources/post.ex, test/test_helper.exs
I implemented it so that the single create returns the existing row.
Any row that was skipped because of the upsert filter clause will have the metadata entry `upsert_skipped` set.
Alternatively we could return `nil`, but I believe that might confuse the users of the function. With bulk creates it makes more sense to be missing.
I couldn't find specific tests for single create / single bulk create. So I added those as well.
This is a prerequisite to implement the syntax sugar from https://github.com/ash-project/ash/issues/1385
=> Handle filter condition on create

lib/verifiers/validate_identity_index_names.ex
`identity.name` is an atom and we don't want to include the `:` in the output in this case.
Before
```
postgres do
identity_index_names :unique_id: "a_shorter_name"
end
```
After
```
postgres do
identity_index_names unique_id: "a_shorter_name"
end
```
=> docs: Output valid example code in ValidateIdentityIndexNames

test/support/test_repo.ex
Allow passing a bare integer as PG_VERSION, which will be interpreted as a major version
=> chore: fix PG_VERSION parsing in tests

lib/migration_compile_cache.ex, lib/multitenancy.ex
I ran into an issue where concurrently creating new tenants in async tests crashed due to ash_postgres attempting to concurrently compile the same tenant migration file.
I attempted to write a regression test as well, but came to the conclusion that it would end up being brittle since it is timing-based and needs multiple DB connections. It would also require me to add a whole new domain with context-based multitenancy instead of attribute-based to the test repo.
=> fix: race condition compiling migrations when concurrently creating new tenants

CHANGELOG.md, README.md, documentation/topics/advanced/manual-relationships.md, documentation/tutorials/get-started-with-ash-postgres.md, lib/functions/trigram_similarity.ex
I'm new to Ash so I'm using documentation extensively. I've noticed links are sometimes leading nowhere.
So here's the fix for that.
=> Fix links in documentation

lib/sql_implementation.ex, lib/type.ex
We have a custom Ash type to help map integer columns in an existing database schema to booleans in Elixir. 
Ash.Type gets us most of the way there, but to support bare attribute filter expressions like `active?` we need to generate a boolean expression for the WHERE clause. This adds another callback to AshPostgres.Type so the implementation can rewrite those expressions when generating the query, eg. with a `? != 0` fragment for our integer-boolean example.
=> improvement: add `postgres_reference_expr` callback to AshPostgres.Type

lib/resource_generator/spec.ex
alter resource generation query to go to the source pg_constraints table instead of to the view to fetch constraint data
This path is already tested, I sadly don't have time to map up duplicate names on references to test now, should maybe add issue to track that chore?
=> fix bug involving duplicate foreign key constraint names across schema

lib/resource_generator/resource_generator.ex, lib/resource_generator/spec.ex
=> Fix query for metadata on foreign keys and fix duplicate references being produced

lib/migration_generator/ash_functions.ex
This is a minor hardening of postgres security, in response to supabase advisor warnings.
It's only been added to the new migration generator, it's not serious enough to try and address elsewhere. This should mean that anyone setting up a new app will get these new settings.
Closes https://github.com/ash-project/ash_postgres/issues/396
@zachdaniel Sorry for the delay posting this! 
- I'm not sure how much further to test this. The changes have been applied to our app for a couple of months, no issues. 
- Tests pass (but I'd be surprised if there was coverage for this minor postgres setting)
- I created a new app, ran the generator and deployed to supabase: can confirm the warnings are gone
Before: 
After:
=> bug: add search path to postgres functions

lib/data_layer.ex, lib/repo.ex
=> feat: add options to disable atomic actions and error expressions

test/cascade_destroy_test.exs, test/support/resources/post.ex
A test for issue #461
fix in https://github.com/ash-project/ash/pull/1734
=> add test for cascade destroy change

lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, lib/mix/tasks/ash_postgres.generate_migrations.ex, test/migration_generator_test.exs
=> Improvement: generate migrations task support concurrent indexes flag

lib/migration_compile_cache.ex, lib/multitenancy.ex
This fixes the problem of logging "redefining module" entries when using context-driven multitenancy (where each tenant tries to compile the migration module).
[Fixes #480]
=> Ignore module conflict when compiling migration file

test/type_test.exs
Custom types aren't being casted in expressions, this is causing both filters as well as joins to fail with a `DBConnection.EncodeError`.
=> Custom types don't work in expressions

lib/repo.ex
Per chat in Discord
Redefine private function as it's causing issue when trying to set up `fly_postgres`
```
2 doctests, 2 properties, 463 tests, 0 failures
```
=> [WIP] Redefine private function, prepare_opts

lib/data_layer.ex
[#1833](https://github.com/ash-project/ash/issues/1833)
With this change output becomes:
```
iex(12)> Ash.create booking
13:26:15.596 [debug] QUERY ERROR source="bookings" db=1.7ms queue=1.3ms idle=1920.5ms
INSERT INTO "bookings" ("start","duration","inserted_at","user_id") VALUES ($1,$2,$3,$4) RETURNING "user_id","inserted_at","duration","start","id" [~N[2025-03-02 11:59:15], 10000, ~U[2025-03-02 12:26:15.581059Z], 1]
{:error,
%Ash.Error.Invalid{
bread_crumbs: ["Error returned from: Bella.Bookings.Booking.create"], 
changeset: "#Changeset<>", 
errors: [
%Ash.Error.Changes.InvalidAttribute{
field: :start,
message: "overlap error",
private_vars: [
constraint: "bookings_cannot_overlap",
constraint_type: :exclusion
],
value: nil,
splode: Ash.Error,
bread_crumbs: ["Error returned from: …
```
=> fix: Use `exclusion_constraint` instead of `check_constraint` in `add_exclusion_constraints`

lib/data_layer.ex
Was getting `Ash.Error.Unknown` from identity constraints in polymorphic resources on violations because table context information was discarded at that place in code and `Ecto.Changeset.unique_constraint` was getting called with wrong constraint names.
=> fix: handle errors from identities in polymorphic resources properly

lib/migration_generator/migration_generator.ex, test/migration_generator_test.exs
When changing attribute with a custom index, recreate the index after table change.
closes https://github.com/ash-project/ash_postgres/issues/259
=> fix: order when renaming attribute with an index

lib/migration_generator/phase.ex, test/migration_generator_test.exs
Create schema (if specified) before creating the table.
Closes https://github.com/ash-project/ash_postgres/issues/247
=> fix: create schema before table creation

lib/mix/tasks/ash_postgres.create.ex, lib/mix/tasks/ash_postgres.drop.ex, lib/mix/tasks/ash_postgres.migrate.ex, lib/mix/tasks/ash_postgres.rollback.ex
=> docs: document `-r` flag in tasks docs

lib/data_layer.ex
Closes https://github.com/ash-project/ash_postgres/issues/459
=> fix: ash postgres subquery usage

lib/migration_generator/operation.ex
A previous index was created with previous tenancy and so when it is being removed it should use it too, not current one.
=> fix: use old multitenancy in generated removals of previous indexes

lib/migration_generator/operation.ex
There were multiple things - in some places `all_tenants?` was ignored when it comes to index keys resolution, in `RemovePrimaryKey` and `RemoveUniqueIndex` a new tenancy was used when old one should been, `where` option was ignored in `RemoveUniqueIndex.down`.
=> fix: fix some issues in migration generator related to tenancy

test/aggregate_test.exs, test/support/resources/post.ex
=> improvement: Expand aggregate test covering rem expression

.tool-versions
Related to [issue](https://github.com/ash-project/ash/pull/2078) I was having.
Might be an issue on my end but with current tools versions on main:
```
erlang 27.0.1
elixir 1.18.4-otp-27
```
I couldn't compile:
```
error: Duration.__struct__/0 is undefined, cannot expand struct Duration. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
lib/ash/type/duration.ex:27: Ash.Type.Duration.matches_type?/2
== Compilation error in file lib/ash/type/duration.ex ==
** (CompileError) lib/ash/type/duration.ex: cannot compile module Ash.Type.Duration (errors have been logged)
lib/ash/type/duration.ex:27: (module)
could not compile dependency :ash, "mix compile" failed. Errors may have been logged …
```
=> bump: tool versions

test/support/resources/post.ex, test/type_test.exs
This commit currently only adds a failing test.
=> fix: add failing test for `type()` in expression

lib/mix/tasks/ash_postgres.drop.ex, lib/mix/tasks/ash_postgres.gen.resources.ex, lib/mix/tasks/ash_postgres.generate_migrations.ex, lib/mix/tasks/ash_postgres.migrate.ex, lib/mix/tasks/ash_postgres.rollback.ex, lib/mix/tasks/ash_postgres.squash_snapshots.ex
=> Fix mix task documentation typos

lib/resource_generator/spec.ex
Small typo I noticed while looking at the code. No idea on the impact. I don't think these are tested or at least I couldn't find any test so I didn't bother with that.
=> fix: smallserial not mapping to proper type

lib/migration_generator/migration_generator.ex
NOTE: I haven't included any testing as it's unclear to me that there exist any tests for default constraint generators. I noticed that at least one previous patch applied to this region didn't include tests. LMK if I should do anything differently.
AshPostgres.Timestamptz creates a pg column of type 'timestamptz', however the existing default behaviour was to implement the default constraint as a 'timestamp' type. Effectively 'now()::timestamptz' was converted to 'timestamp' then back to 'timestamptz'. This has been changed to 'now()'.
=> fix: use default constraint of 'now()' for AshPostgres.Timestamptz

test/aggregate_test.exs, test/support/resources/post.ex
=> test: write failing test to illustrate regression

.tool-versions, documentation/topics/development/migrations-and-tasks.md
For context on `mise` and `.tool-verions`: If a higher version of OTP is available for an Elixir version than the selected Erlang version, it results in an OTP mismatch error.
=> chore: remove deprecated script documentation; fix mise confusion in .tool-versions

lib/migration_generator/migration_generator.ex, lib/resource_generator/resource_generator.ex, lib/resource_generator/spec.ex, test/resource_generator_test.exs
This PR fixes the resource generator to properly handle tables in non-public PostgreSQL schemas (e.g., `inventory.products`, `ocloud.roles`). Previously, the generator would fail when attempting to introspect tables outside the `public` schema. e.g.:
```
mix ash_postgres.gen.resources OgatApp.AshDomains.GrantedRoles --tables ocloud.roles --snapshots-only
Generating resources from [OgatApp.Repo]
** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "roles" does not exist
(ecto_sql 3.13.2) lib/ecto/adapters/sql.ex:1098: Ecto.Adapters.SQL.raise_sql_call_error/1
(ash_postgres 2.6.20) lib/resource_generator/spec.ex:127: AshPostgres.ResourceGenerator.Spec.add_foreign_keys/1
(ash_postgres 2.6.20) lib/resource_generator/spec.ex:113: anonymous fn/1 in …
```
=> fix: Support non-public PostgreSQL schemas in resource generator
