ash-project/ash_postgres

lib/ash_postgres.ex
the branch was named generate resource, but the work done was just for adding Postgres table concept
=> Postgres Tables

lib/migration_generator/migration_generator.ex
=> fix: don't group alters with creates

lib/migration_generator/migration_generator.ex
Allows to create a binary custom type.
I'm not sure what you would like to see in the way of tests?
=> Add :binary migration type

lib/migration_generator/migration_generator.ex
Please let me know if PRs for such little things are overkill, I will then just collect them and send them at once :)
=> Remove parentheses

lib/mix/tasks/ash_postgres.generate_migrations.ex
=> chore: fix typos

README.md
It was difficult to follow the docs as written so I filled them out.
=> docs: Update docs in readme

lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, mix.exs, test/migration_generator_test.exs
=> handle when no opts are passed to custom index

lib/data_layer.ex
Signed-off-by: kernel-io <kernel>
=> fix: ensure we are returning * on upserts

lib/migration_generator/migration_generator.ex
ensure repo is compiled before generating snapshots
=> bugfix: ensure repo is compiled

lib/ecto_migration_default.ex, test/migration_generator_test.exs
=> improvement: support float as Ecto migration default

lib/ecto_migration_default.ex, test/migration_generator_test.exs
=> improvement: add decimal ecto migration default

test/support/resources/comment.ex, test/support/resources/post.ex
Fixes breaking build introduced by https://github.com/ash-project/ash/commit/74cc7c4ad5158dd1989cdca88f0d08b5e8df6dbc
=> fix: ensure all single actions are explicitly marked as primary?

lib/mix/tasks/ash_postgres.generate_migrations.ex
=> docs: Fix docs for `name` option to `generate_migrations`

documentation/tutorials/get-started-with-postgres.md
Added comments to iex examples that explain what the result of the queries are.
=> docs: Add explanation comments to the examples

documentation/tutorials/get-started-with-postgres.md
Changed references to `Helpdesk.Tickets` to `Helpdesk.Support` and fixed file paths to reflect new file structure.
=> docs: Change to Helpdesk.Support to match other guides

documentation/tutorials/get-started-with-postgres.md
Changed `Helpdesk.Tickets` to `Helpdesk.Support` and fixed file comments to reflect the change.
=> docs: change API to Helpdesk.Support

lib/join.ex
=> fix: don't use hard-coded join assoc name

documentation/tutorials/get-started-with-postgres.md
=> style: make the title heading level 1

documentation/tutorials/get-started-with-postgres.md
- Add Helper Text
- Fix Link to AshPostgres DSL
=> docs: Update Getting Started Document

documentation/tutorials/get-started-with-postgres.md
I hope this is the right way to propose a change to the docs, and think the items on the checktlist don't apply.
=> docs: improve postgres documentation code

test/bulk_create_test.exs
- There were two tests that were already broken
- Broken test added for bulk creating relationships
=> test: add test for bulk creating relationships

lib/migration_generator/migration_generator.ex, test/migration_generator_test.exs
=> fix: Fixes multiple schema identities migrations

lib/data_layer.ex
=> fix protected names in conflict_target

lib/expr.ex
=> remove IO.inspect

documentation/how_to/using-fragments.md
:wave: 
I added some examples of fragment to the documentation.
=> doc: Add more fragment examples

lib/migration_generator/operation.ex
=> Support all_tenants? in custom index

lib/migration_generator/migration_generator.ex
This PR just makes MigrationGenerator a little bit more flexible my making it accept either atoms or strings (that needs to be converted to atoms) for some of the values.
=> feat: Make MigrationGenerator accept atoms

test/filter_field_policy_test.exs, test/support/resources/organization.ex, test/support/resources/post.ex
test that shows the behviour that should be fixed by https://github.com/ash-project/ash/pull/888
=> add test to show problem with field policies in filters

test/filter_test.exs
Wrote a failing test.
Didn't fix bug.
=> test: filter by has_one from_many?

lib/data_layer.ex
`row in resource` does not work for polymorphic resources. Need to transfer a table too if it is present.
=> fix: properly transfer table names to non-inner wrapper queries

lib/migration_generator/migration_generator.ex
=> Fix migration generator extensions in multiple repos

lib/migration_generator/operation.ex
=> Merge base_filter and custom index's where correctly

.formatter.exs, documentation/dsls/DSL:-AshPostgres.DataLayer.md, lib/custom_index.ex, lib/migration_generator/migration_generator.ex, lib/migration_generator/operation.ex, test/migration_generator_test.exs
This is a duplicate of PR #175, but it seems that the mentioned PR is no longer progressing, so I am posting it again.
The DSL documentation appears to be automatically generated. How can I update it?
=> Add nulls_distinct option to CustomIndex

lib/data_layer.ex
Implementation and resource were swapped at some call sites
=> fix: fix argument order in AshSql.Bindings.default_bindings/4

documentation/topics/development/testing.md
=> docs: Fix typo in page title

lib/migration_generator/migration_generator.ex
=> Fix resolve_renames that keeps columns to be renamed in adding list.

documentation/tutorials/get-started-with-ash-postgres.md
Just a couple changes I needed to make as I was following the tutorial:
- Use newer `ash_postgres` version since old version had dependency resolution errors
- Change path of Helpdesk resources to match the examples seen in the main Ash `Get Started` tutorial.
- Use `Ash.read/update/load` instead of `Helpdesk.Support.read/update/load` since the compiler was giving deprecation warnings
- Fix wording at the end to avoid using confusing double-negatives
I think my changes are accurate, but should probably be double checked by someone who is more familiar with Ash. Thanks.
=> docs: change 'Get Started' guide for Ash 3.0 compatibility

test/filter_test.exs
Filtering on ref in this manner worked up until Ash 3.0. Now, it gives the following error:
1) test filter with ref (AshPostgres.FilterTest)
test/filter_test.exs:1076
** (FunctionClauseError) no function clause matching in Ash.Filter.check_filterable/2
The following arguments were given to Ash.Filter.check_filterable/2:
AshPostgres.Test.Organization
:id
Attempted function clauses (showing 2 out of 2):
defp check_filterable(_resource, [])
defp check_filterable(resource, [relationship | rest])
code: |> Ash.Query.filter(^ref(:id, [:posts, :comments]) == ^comment.id)
stacktrace:
(ash 3.0.1) lib/ash/filter/filter.ex:2944: Ash.Filter.check_filterable/2
(ash 3.0.1) lib/ash/filter/filter.ex:2933: anonymous fn/2 in Ash.Filter.validate_filterable_relationship_paths/2
(elixir 1.16.2) …
=> test: add failing test to demonstrate error using ref

test/bulk_destroy_test.exs, test/filter_test.exs
They were using an :update action
=> chore: fix bulk destroy tests

test/load_test.exs
Drafted until https://github.com/ash-project/ash/pull/1183 gets merged
=> chore: add tests for paginated relationship count

test/support/relationships/filter_child_relationship_by_parent_relationsip.ex, test/support/resources/comment.ex
=> test demonstrating issue filtering relationship by parent

test/sort_test.exs
Tried to come up with this test as close to my scenario as possible.
I'm not even sure if the second assert works but it gives the error I'm seeing in our app.
=> Add a failing test for sorting on relationship

lib/mix/tasks/ash_postgres.create.ex, lib/mix/tasks/ash_postgres.drop.ex
=> Fix Elixir 1.17 warnings

lib/migration_generator/migration_generator.ex
This makes order of keys in a snapshot stable. Easier for computer and human eye to diff.
Note: There is [`StableJason`](https://github.com/egze/stable_jason) (which does the same thing but because of need to support structs, which snapshot does not use, it instead encodes -> decodes -> orders -> encodes). Upside is that the change would have looked even smaller but don't know if a dependency is worth it in this case.
=> improvement: order keys in snapshot json

lib/data_layer.ex
=> chore: fix 1.17 warning

lib/mix/tasks/ash_postgres.install.ex
=> improvement: add DataCase creation for igniter installer

test/complex_calculations_test.exs, test/support/complex_calculations/resources/documentation.ex, test/support/complex_calculations/resources/skill.ex
=> replicate error when building json object and using inline aggregate

lib/data_layer.ex
=> fix: allow non-unique has_many source_attributes

test/atomics_test.exs, test/support/resources/post.ex
=> test more aggregates in validations

test/atomics_test.exs, test/support/resources/post.ex
=> test validation aggregates individually as well

documentation/topics/development/migrations-and-tasks.md
Add missing filter to account for resources without repo
=> documentation: add filter for nil repos

lib/types/timestamptz.ex
~~- [ ] Bug fixes include regression tests~~
~~- [ ] Features include unit/acceptance tests~~
=> docs: fix typo in timestamptz

documentation/topics/development/migrations-and-tasks.md
Fix https://github.com/ash-project/ash_postgres/issues/407
The previous suggested code only works locally. The updated one works in both dev and prod env. 
Tested on fly.io docker deployment.
=> doc: Fix migration path for tenant migration

documentation/topics/advanced/expressions.md
This PR fixes a typo in the doc
=> fix type in docs

documentation/tutorials/get-started-with-ash-postgres.md
=> docs: Fix old code in Getting Started guide

test/update_test.exs
=> Add test: loaded relationships remain loaded after update

lib/mix/tasks/ash_postgres.drop.ex
=> docs: use proper flag in ash postgres drop example

lib/mix/helpers.ex, lib/mix/tasks/ash_postgres.create.ex, lib/mix/tasks/ash_postgres.drop.ex, lib/mix/tasks/ash_postgres.migrate.ex, lib/mix/tasks/ash_postgres.rollback.ex
=> improvement: propagate `-r` flag to Ecto

documentation/topics/resources/references.md
Just a small docs improvement I was personally struggling with. 
- [x ] Bug fixes include regression tests
- [ x] Features include unit/acceptance tests
=> docs: Added link to all supported reference options

lib/migration_generator/migration_generator.ex, test/migration_generator_test.exs
=> fix: correct order, when renaming attribute with an identity

documentation/topics/advanced/manual-relationships.md
The previous commit for https://github.com/ash-project/ash_postgres/issues/540 set `employee.descendants` as `[]`.
I think you meant to do `Enum.group_by`.
=> edit manual relationships example with group_by and relationship name

test/rel_with_parent_filter_test.exs, test/support/resources/post.ex
=> test that shows that parent stacking works in general but not with filter

documentation/topics/advanced/schema-based-multitenancy.md
Learning Ash and felt like this section could have used an example so here's one.
=> docs: add example all_tenants implementation

lib/mix/tasks/ash_postgres.migrate.ex
=> fix: retain repo as atom in migrator task

lib/data_layer.ex
=> fix: double select error

documentation/topics/development/migrations-and-tasks.md
=> fix: list_tenants -> all_tenants
